### ISSUE TITLE
Logo competition

### ISSUE THREAD

**Issue by jessicacoates** [creativecommons/global-summit-#20]
design and run the logo competition; obtain assignment of logo

**Comment by soohyunpae** [comment]
CC Korea team has been planning to make a short announcement about the logo competition on its local  GS website (to be published tomorrow) with dates (May 11 to May 30) and without details about the process and prize. As Nanshil suggested earlier, our original plan is to use the process of the previous competitions and to add a public voting component to it.
But @janeatcc threw in a good idea about tying in MOMA and NP in the brainstorming doc. We'd happy to hold the announcement until we agree on the details.

**Comment by jessicacoates** [comment]
Why don't you write to Jane and Jay to see if they have any specific ideas - I like the idea, but I can't think of anything more significant than mentioning them in the announcement.

We can copy whatever you put together on the HQ GS website - we should coordinate those two, to make sure they have the same information. Have you talked to Matt about what you're doing with your site?

Also - I'm assuming as well as publishing you were going to publicise to the affiliates? They need to be kept up with everything - normally we'd tell them in advance.

**Comment by janetpkr** [comment]
@jayaw what do you think?
I think mentioning them at the very least is important. 

Maybe if we encourage them to do something akin to the NP's icon? or get build on that? Don't want to be too constraining though. Whatever guidelines @jayaw and @peterspdx develop should guide derivations in this competition

**Comment by soohyunpae** [comment]
@jessicacoates Yes, our developer Youngtaek contacted Matt to see how the local GS website can be tied to HQ GS website and how we can coordinate the two.

The local GS site basically has only two features - email update sign-up and a notice that a logo competition will come up soon. We want to launch the website sooner than later to raise interest in public. How about locking down the application dates (say May 11 to June 1) now and deciding competition policies and rules by next week? 

[Updates]
Our team discussed this issue and replaced the dates of the logo competition with TBA. @mattl please review @mozodev's pull request and let us know when it will go live.

**Comment by soohyunpae** [comment]
@janeatcc +1 to we should be careful not to be too constraining.

**Comment by soohyunpae** [comment]
FYI, here's the original plan copied and revised from the last summit:
- Application period: May 1 to May 31
- 1st round: GS organising team (HQ + CC Korea) select 10 designs
- 2nd round: CC affiliates select 5 designs
- 3rd round: Public voting
- Prize: 500 USD

@jessicacoates did we use any voting tool in the past? CC Korea is looking into ways to incorporate a voting system into the Korean GS website (and attaching it to HQ GS website), and we won't have to if there is a tool we've used before.

**Comment by jayaw** [comment]
Hi @soohyunpae @janeatcc @jessicacoates  - just speaking frankly from the get-go (and understand that I'm really not versed in the history of Global Summit organizing), based on my experience with logo competitions they don't usually operate efficiently or quickly, and sadly they're never really fair to good design or designers. They are definitely an option - so I'm not suggesting you rule them out - and in some situations they work well, for example when there is a large pool of folks interested in design or people who generally work on logos pretty regularly (this was the case in the Wikimedia space, where lots of people volunteers liked to design/sketch in that manner). If there's confidence that this kind of a community is standing by, then I'd say it's worth a shot, but given short timelines I'm not sure it would get you exactly what you need.

Another option is to reach out to one person who has interest/time/experience in visual identity/design who is within the community and ask them if they'd like to present an overall visual identity (because ultimately the logo is just one part of the system). They could make a few sketches, the committee could narrow it down, offer notes, and then get to a final design that works. This could be pro-bono work for any designer if they'd like a fun and meaningful way to build their portfolio. You could invite any interested parties to offer some rough sketch/idea rather than a final design (Which is more common in logo competitions).

Just wanted to share those perspectives at this stage if it's helpful. I'm happy to elaborate.

Either way, yes, you could mention the recent work from MOMA (Which is really just a recognition of the wonderful double-c logo and its associates) and Noun Project (which was their effort to develop a great concept that celebrates the CC logo). I suppose it could be something like "Creative Commons has a globally recognized and celebrated visual identity, and this is your opportunity to bring your creativity and skill to help us produce a unique identity for the global summit." And from there you could point to Noun Project's work as an example of a great exploration of the CC identity.

I know with Wikimania (Wikimedia's annual event) there is always an effort to create some kind of locally significant mark (http://commons.wikimedia.org/wiki/Category:SVG_Wikimania_logos). But not sure if that's the norm for the global summit. Certainly I can see how designers would be excited to tie together the locale and the CC identity.

I know that's a lot to process - hope it's useful, and forgive me if I'm stumbling over anything important.

**Comment by mattl** [comment]
Yeah, see nospec.com

**Comment by jessicacoates** [comment]
@jayaw I think we've always seen the logo competition as a community development/involvement opportunity in the past, rather than being too worried about getting the best logo possible. We've usually got less than 20 entries (off the top of my head), most of which aren't great (there are some very different aesthetics around the world), but have been very happy with what we've ended up with (see the logos for the last Summits). I'd love to keep it unless we are particularly rushed or concerned about quality. Happy to be overruled by others, especially about the importance of getting just the right logo - does @ryanmerkley have an opinion? 

@soohyunpae - assuming it does go ahead, I'm happy with the same process we did before. Though I'm surprised at the order of the voting - did we really do it that way? Who knew! I'm happy for you to work out the process - this one is your thing. For voting tools in the past, Chiaki set it up through her website the first year, and I'm sure there was something fairly easy online that Val etc found last year - maybe just facebook and email if you're not on that?

**Comment by soohyunpae** [comment]
The logo competition website will be launched by the end of this week.
Here's a draft announcement for the website: https://docs.google.com/document/d/1L1uW30olOTa6MCZTdZcHya9DDuivuyfueOAgSJ4CGQ8/edit
Feel free to edit the text or add comments if you have any suggestion!

**Comment by peterspdx** [comment]
I edited and left a comment.  We have always required that all rights in the winning logo be assigned to Creative Commons, in consideration for the cash prize.  I don't see any reason to change that here.  Using copyright licenses for trademarks and logos (especially one that will almost assuredly use one of our protected logos such as the double-c in a circle logo) is not a good practice.  Let me know if you have questions or if you'd like to see the form assignments we've used in years past.

**Comment by peterspdx** [comment]
I appreciate that to some this make appear heavy handed, but it isn't, and nobody has objected but instead appreciate that logos are brand identifiers.  It should be treated as such.  We have liberal policies for reuse of the logos on our /policies page, and one item in the queue from our collaboration with jw has been to get these special logos up on a page somewhere with specific reuse permissions associated with them.  That's still a to-do.  

And as for the difference and why that's relevant, see this FAQ:  https://wiki.creativecommons.org/FAQ#Could_I_use_a_CC_license_to_share_my_logo_or_trademark.3F

(Updated edit: there's a link broken in the FAQ noted above, but see this FAQ also, which also explains that our licenses don't grant TM permissions): https://wiki.creativecommons.org/FAQ#Can_I_place_a_trademark_on_a_work_and_offer_the_work_under_a_CC_license_without_also_licensing_or_otherwise_affecting_rights_in_the_trademark.3F_If_so.2C_how.3F

**Comment by pgstacey** [comment]
Ah, I see, thanks for the clarification Diane.
Paul

On Wed, Jun 3, 2015 at 6:15 AM, Diane Peters notifications@github.com
wrote:

> I appreciate that to some this make appear heavy handed, but it isn't, and
> nobody has objected but instead appreciate that logos are brand
> identifiers. It should be treated as such. We have liberal policies for
> reuse of the logos on our /policies page, and one item in the queue from
> our collaboration with jw has been to get these special logos up on a page
> somewhere with specific reuse permissions associated with them. That's
> still a to-do.
> 
> And as for the difference and why that's relevant, see this FAQ:
> https://wiki.creativecommons.org/FAQ#Could_I_use_a_CC_license_to_share_my_logo_or_trademark.3F
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativecommons/global-summit-/issues/20#issuecomment-108402092
> .

## 

Paul Stacey
Associate Director of Global Learning
Creative Commons
pstacey@creativecommons.org

State of the Commons Report https://stateof.creativecommons.org/report/
Get Creative Commons Updates http://bit.ly/commonsnews

**Comment by soohyunpae** [comment]
Thanks @peterspdx 
I revised the text as suggested. Can you please have a look at my comments in the document regarding the license/copyright agreement?

@mattl we're currently developing the logo competition website and hope to launch it by the end of this week (the competition starts on Monday, Jun 7 and ends on Jun 30 UTC.)
Please expect a pull request from @mozodev tonight and let us know whether it can be done by Friday. If it can't be done in time, we'd like to put it under CCKorea's domain. And a short announcement with a link to the logo competition webpage before Monday would be great.

**Comment by peterspdx** [comment]
@soohyunpae I checked the language in the document, and responded to your comment there.  To reiterate, I would prefer the logos that are not the winning logos be posted on our website or on CC Korea's website rather than to Flickr under a CC license.  See above response to pgstacey for why applying a (c) license to a logo is suboptimal.  I suppose that to the extent the logo doesn't include one of CC's protected marks, it's fine.  But I would strongly prefer any logos using ours not be CC-licensed for the reasons stated.

**Comment by soohyunpae** [comment]
@mattl Can you add an announcement and a link to the logo competition page (http://logo.cckorea.org) to the summit website? Thanks!

**Comment by mattl** [comment]
Can we make some changes to that page?

First, let's not ask people to submit a JPEG, when a logo would look awful
in that format. A PNG will be better.

Second, let's not assume the world uses proprietary software. Let's ask for
submissions in an open format, like SVG.

Finally, we need to get that page under HTTPS. Happy to talk to whomever we
need to make that happen.

**Comment by mozodev** [comment]
@mattl please review my PR https://github.com/creativecommons/global-summit-/pull/31
and done with https://logo.cckorea.org! Thanks!

**Comment by mattl** [comment]
All set and it's up on the site :)

---

Matt Lee
Creative Commons
Boston, MA, USA

**Comment by tvol** [comment]
I shared on Twitter (https://twitter.com/creativecommons/status/611585606083194881) and Facebook.
