### ISSUE TITLE
Create basic summit website for launch

### ISSUE THREAD

**Issue by ryanmerkley** [creativecommons/global-summit-#8]
Starting this issue to identify MVP components for the summit launch site. It should include:
- sign-up form to get more information (e-mail signup)
- date, location
- "about the conference" info that helps people figure out if the conference is for them

What else?

**Comment by mattl** [comment]
The form I have currently adds people to a group in CiviCRM, so we can send them update emails.

Do we also want a place to discuss the summit?

Do we want a CFP?

**Comment by mattl** [comment]
Looping @jessicacoates and @jayaw on this too.

**Comment by ryanmerkley** [comment]
What's a CFP?

**Comment by mattl** [comment]
Sorry, Call for Papers.

**Comment by ryanmerkley** [comment]
Yes, a call for papers is good, though that term feels really academic. I'd like people to feel like they could propose a discussion or workshop without having to write an academic paper.

**Comment by mattl** [comment]
Yeah, I'll work on some text, more MozFest than SIGGRAPH.

**Comment by jessicacoates** [comment]
Happy with all this - though previously I think we've staggered the call for papers with the launch. Also should discuss what we want them to provide - I think we had a form last time where we got them to specify if it was a workshop, talk etc. Need to check with Korea too. 

My suggestion is that we aim to launch the registration and call for papers at the end of April, rather than including it in this initial launch. Maybe mention that there will be a call for papers soon, so that people can start thinking of ideas.

**Comment by jessicacoates** [comment]
Happy with all this - though previously I think we've staggered the call for papers with the launch. Also should discuss what we want them to provide - I think we had a form last time where we got them to specify if it was a workshop, talk etc. Need to check with Korea too. 

My suggestion is that we aim to launch the registration and call for papers at the end of April, rather than including it in this initial launch. Maybe mention that there will be a call for papers soon, so that people can start thinking of ideas.

**Comment by jessicacoates** [comment]
Here's the form we used for CFP last time - aiming for enough info to be able to schedule without going back to ask for more details.https://docs.google.com/a/creativecommons.org/forms/d/1Fd-oreSn0HwPsrLdMCaX6dkA7EFINmbgEOuPILmVcaE/edit?chromeless=1

can be useful if we have an idea about tracks first too; or we can base tracks on talks submitted.

**Comment by soohyunpae** [comment]
This is small, but '한국어' sounds more natural than '한국말' for a written text ;) @mattl

**Comment by tvol** [comment]
@mattl https://summit.creativecommons.org/cfp/ says summit runs oct 14-17 when big text at top says 15-17. let's make it say the same.

**Comment by mattl** [comment]
Can we please not reopen old issues for new things?
